
#開発環境用の設定

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: protospace_41361_development

test:
  <<: *default
  database: protospace_41361_test

production:
  <<: *default
  database: protospace_41361_production
  username: protospace_41361
  password: <%= ENV["PROTOSPACE_41361_DATABASE_PASSWORD"] %>

  
#本番アップ用の設定

  default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_41361_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_41361_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
